### ISSUE TITLE
Will the project be updated?

### ISSUE THREAD

**Issue by lxacc** [Kathess/DYRECTsn#1]
Will the project be updated?

**Comment by Kathess** [comment]
Yes absolutely! 👍 
Just a few more days, I am sorry for the slight delay.

**Comment by lxacc** [comment]
Looking forward to it. Thank you
---- Replied Message ----
From ***@***.***> Date 03/09/2024 00:34 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [Kathess/DYRECTsn] Will the project be updated? (Issue #1) 
Yes absolutely! 👍
Just a few more days, I am sorry for the slight delay.

**Comment by Kathess** [comment]
All set up! Thank you for the patience.
Have fun and best regards :)
